apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  namespace: shoppingportal
  labels:
    app: zipkin-svc
spec:
  selector:
    app: zipkin
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 9411